apiVersion: v1
kind: Service
metadata:
  name: trademarkcontainerregistry
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: trademarkcontainerregistry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
